---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/parks":
    get:
      summary: list parks
      responses:
        '200':
          description: successful
    post:
      summary: create park
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              properties:
                name:
                  type: string
                nearest_town:
                  type: string
                state:
                  type: string
                area:
                  type: integer
                designated:
                  type: string
              required:
              - name
              - nearest_town
              - state
              - area
              - designated
  "/parks/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show park
      responses:
        '200':
          description: successful
    patch:
      summary: update park
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              properties:
                name:
                  type: string
                nearest_town:
                  type: string
                state:
                  type: string
                area:
                  type: integer
                designated:
                  type: string
    put:
      summary: update park
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              properties:
                name:
                  type: string
                nearest_town:
                  type: string
                state:
                  type: string
                area:
                  type: integer
                designated:
                  type: string
    delete:
      summary: delete park
      responses:
        '200':
          description: successful
  "/parks/random":
    post:
      summary: create random park
      responses:
        '200':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000/
